# SPDX-FileCopyrightText: 2026 Benjamin Förster
# SPDX-License-Identifier: EUPL-1.2 OR LicenseRef-PHIDS-Commercial

"""Unit Invariant Tests for Numba JIT Power-of-Two Neighbour Gathering Equivalence.

This module validates that power-of-two bitwise AND coordinate wrapping ((x - 1) & mask_x)
produces bit-exact identical neighbour arrays to generic modulo coordinate wrapping ((x - 1) % width).
"""

from __future__ import annotations

import numpy as np
import pytest

from phids.engine.systems.interaction.movement import (
    _gather_neighbours_jit,
    _gather_neighbours_jit_pow2,
)


@pytest.mark.jit_parity
def test_numba_jit_gather_neighbours_parity() -> None:
    """Verify power-of-two bitwise neighbour gathering matches standard modulo gathering exactly.

    Raises:
        AssertionError: If neighbour coordinates generated by bitwise AND mask differ from modulo wrapping.
    """
    width, height = 16, 16
    mask_x, mask_y = width - 1, height - 1

    cx_mod = np.zeros(5, dtype=np.int32)
    cy_mod = np.zeros(5, dtype=np.int32)
    cx_pow2 = np.zeros(5, dtype=np.int32)
    cy_pow2 = np.zeros(5, dtype=np.int32)

    # Test center cell (5, 5)
    _gather_neighbours_jit(5, 5, width, height, cx_mod, cy_mod)
    _gather_neighbours_jit_pow2(5, 5, mask_x, mask_y, cx_pow2, cy_pow2)
    np.testing.assert_array_equal(cx_mod, cx_pow2)
    np.testing.assert_array_equal(cy_mod, cy_pow2)

    # Test boundary corner cell (0, 0)
    _gather_neighbours_jit(0, 0, width, height, cx_mod, cy_mod)
    _gather_neighbours_jit_pow2(0, 0, mask_x, mask_y, cx_pow2, cy_pow2)
    np.testing.assert_array_equal(cx_mod, cx_pow2)
    np.testing.assert_array_equal(cy_mod, cy_pow2)


@pytest.mark.jit_parity
def test_numba_jit_flow_field_pow2_parity() -> None:
    """Verify flow field relaxation with power-of-two bitwise AND masking matches modulo relaxation exactly."""
    from phids.engine.core.flow_field import (
        _propagate_iteration_jit,
        _propagate_iteration_jit_pow2,
    )

    width, height = 32, 32
    mask_x, mask_y = width - 1, height - 1
    decay = 0.60

    np.random.seed(123)
    base = np.random.randn(width, height)
    current = np.random.randn(width, height)
    nxt_mod = np.zeros((width, height), dtype=np.float64)
    nxt_pow2 = np.zeros((width, height), dtype=np.float64)

    diff_mod = _propagate_iteration_jit(width, height, decay, base, current, nxt_mod)
    diff_pow2 = _propagate_iteration_jit_pow2(width, height, mask_x, mask_y, decay, base, current, nxt_pow2)

    np.testing.assert_allclose(diff_mod, diff_pow2, rtol=1e-12, atol=1e-12)
    np.testing.assert_allclose(nxt_mod, nxt_pow2, rtol=1e-12, atol=1e-12)
